source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'GoGoApp' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport',
    'ART'
  ]
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  #facebook sdk
  # pod 'Bolts'
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKShareKit'
  # pod 'FBSDKLoginKit'

  # pod 'Firebase/Core'
  # pod 'Firebase/Messaging' #noftification

  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'  # Remove this line if you don't want to support GoogleMaps on iOS
  # pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  # pod 'Google-Maps-iOS-Utils'

  # pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
  # pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS

  # add lotties
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'react-native-maps', path: '../node_modules/react-native-maps/'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'



end
post_install do |installer|
  installer.pods_project.targets.each do |target|
#      if target.name == "react-native-google-maps"
#          target.build_configurations.each do |config|
#              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#          end
#      end
      if target.name == "React"
        target.remove_from_project
      end
  end
end
